"""
Live-event traffic simulator for EVCP.

Drives realistic activity against the running backend so Prometheus/Grafana panels move:
dashboard polling, volunteer check-ins/check-outs at the gates, and crowd incidents that get
reported, acknowledged and resolved. Incidents it creates are always resolved again, and
check-ins are balanced by check-outs, so the demo data doesn't drift.

    python simulation/traffic_simulator.py                 # runs until Ctrl+C
    python simulation/traffic_simulator.py --interval 1    # faster ticks
"""
import argparse
import random
import sys
import time

import requests

INCIDENTS = [
    ("Crowd bottleneck forming", "CROWD", "HIGH"),
    ("Attendee feeling faint near stage", "MEDICAL", "CRITICAL"),
    ("Lost child reported", "SECURITY", "HIGH"),
    ("Water station running low", "LOGISTICS", "MEDIUM"),
    ("Barrier section loose", "SAFETY", "MEDIUM"),
]
ZONES = ["North Gate", "Main Stage", "Food Court", "Medical Tent", "South Gate"]

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--api", default="http://127.0.0.1:8000/api")
    p.add_argument("--interval", type=float, default=2.0, help="seconds between ticks")
    args = p.parse_args()
    s = requests.Session()
    open_incidents = []  # (issue_id, ticks_until_next_step)
    tick = 0
    print(f"Simulating live event traffic against {args.api} (Ctrl+C to stop)")

    try:
        while True:
            tick += 1
            try:
                # Coordinators' dashboards poll constantly.
                for path in ("/dashboard/metrics", "/tasks", "/issues", "/announcements", "/volunteers"):
                    s.get(args.api + path, timeout=5)

                # Gate activity: toggle a random volunteer's presence.
                if tick % 2 == 0:
                    vols = s.get(args.api + "/volunteers", timeout=5).json()
                    if vols:
                        v = random.choice(vols)
                        checked_in = str(v.get("status", "")).upper().replace(" ", "_") == "CHECKED_IN"
                        action = "check-out" if checked_in else "check-in"
                        r = s.post(f"{args.api}/volunteers/{v['id']}/{action}", timeout=5)
                        if r.status_code == 400:  # status label didn't match; try the other action
                            action = "check-in" if checked_in else "check-out"
                            r = s.post(f"{args.api}/volunteers/{v['id']}/{action}", timeout=5)
                        print(f"[gate] {action:9} {v.get('full_name', v['id'])}: {r.status_code}")

                # Occasionally something happens in the crowd.
                if random.random() < 0.15 and len(open_incidents) < 3:
                    title, kind, prio = random.choice(INCIDENTS)
                    zone = random.choice(ZONES)
                    r = s.post(args.api + "/issues", timeout=5, json={
                        "title": f"[SIM] {title} at {zone}", "description": "Generated by traffic_simulator.py",
                        "zone": zone, "issue_type": kind, "priority": prio, "event_id": 1,
                    })
                    if r.ok:
                        open_incidents.append([r.json()["id"], random.randint(3, 8), "OPEN"])
                        print(f"[incident] reported #{r.json()['id']} {title} at {zone} ({prio})")

                # Coordinators work the incident queue: acknowledge, then resolve.
                for inc in list(open_incidents):
                    inc[1] -= 1
                    if inc[1] > 0:
                        continue
                    if inc[2] == "OPEN":
                        s.post(f"{args.api}/issues/{inc[0]}/acknowledge", timeout=5)
                        inc[1], inc[2] = random.randint(3, 8), "ACK"
                        print(f"[incident] acknowledged #{inc[0]}")
                    else:
                        s.post(f"{args.api}/issues/{inc[0]}/resolve", timeout=5)
                        open_incidents.remove(inc)
                        print(f"[incident] resolved #{inc[0]}")
            except requests.RequestException as e:
                print(f"[warn] backend unreachable: {e.__class__.__name__}")
            time.sleep(args.interval)
    except KeyboardInterrupt:
        pass
    finally:
        for inc in open_incidents:
            try:
                s.post(f"{args.api}/issues/{inc[0]}/resolve", timeout=5)
            except requests.RequestException:
                pass
        print("Traffic simulator stopped.")


if __name__ == "__main__":
    main()
